const BLOCK_DATA = {
    NORMAL: 1,
    CARPET: 2,

    HALF_BLOCK: 3.0,

    STAIR_BLOCK_DOWN_X_PLUS: 4.0,
    STAIR_BLOCK_DOWN_X_MINUS: 4.1,
    STAIR_BLOCK_DOWN_Z_PLUS: 4.2,
    STAIR_BLOCK_DOWN_Z_MINUS: 4.3,
    STAIR_BLOCK_UP_X_PLUS: 4.4,
    STAIR_BLOCK_UP_X_MINUS: 4.5,
    STAIR_BLOCK_UP_Z_PLUS: 4.6,
    STAIR_BLOCK_UP_Z_MINUS: 4.7,

    SNOW: 5.0,

    WOOD_FENCE: 6.0,

    GLASS_IRON_FENCE: 7.0,

    STONE_FENCE: 8.0,

    END_PORTAL: 9.0,

    PRESSURE_PLATE: 10.0,

    ENCHANTING_TABLE: 11.0

}

export { BLOCK_DATA }