const BLOCK_DATA = {
    NORMAL: 1,
    CARPET: 2,
    HALF_BLOCK_UP: 3.0,
    HALF_BLOCK_DOWN: 3.1,
    STAIR_BLOCK_DOWN_X_PLUS: 4.0,
    STAIR_BLOCK_DOWN_X_MINUS: 4.1,
    STAIR_BLOCK_DOWN_Z_PLUS: 4.2,
    STAIR_BLOCK_DOWN_Z_MINUS: 4.3,
    STAIR_BLOCK_UP_X_PLUS: 4.4,
    STAIR_BLOCK_UP_X_MINUS: 4.5,
    STAIR_BLOCK_UP_Z_PLUS: 4.6,
    STAIR_BLOCK_UP_Z_MINUS: 4.7,
}

export { BLOCK_DATA }